service: atypical
app: atypical
org: dalex
provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
plugins:
  - serverless-offline

